### ISSUE TITLE
Doduo / Dodrio textures error

### ISSUE THREAD

**Issue by Glopeur** [Thutmose/Pokecube-Mobs#10]
Doduo & Dodrio's textures don't apply to the Pokemob
![2018-05-20_15 38 24](https://user-images.githubusercontent.com/35874673/40279507-15134f80-5c44-11e8-9eb4-150ff44c030f.png)

**Comment by Thutmose** [comment]
What version of pokecube core do you have? This should have been fixed in one of the recent ones

**Comment by Glopeur** [comment]
pokecube-revival-1.12.2-6.14.19
pokecube-mobs-1.12.2-4.9.0
pokecube-core-1.12.2-6.36.12

If you already fixed it, that's my bad for not being up to date

**Comment by Thutmose** [comment]
Try updating, it should be fixed, if it isn't, let me know

**Comment by Glopeur** [comment]
Updated and it work.

I'm sorry to bother you with things you already fixed.

------

By the way, is there a thread where I can write some idea to improve the mod ?

**Comment by Thutmose** [comment]
Just make an issue with the suggestions, I will label it accordingly, please give as much detail as possible about what you are suggesting.
