### ISSUE TITLE
significance of the characters above the mobs?

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube-Mobs#8]
Not sure what the significance is of the rotating characters above the Level # of the pokecube mob.  Why is it rotating or needed?
![image](https://user-images.githubusercontent.com/10309346/34459551-3381e1e4-edc1-11e7-9060-693dbef2ccc7.png)

Also, instead of showing the full ID as is, can we change it so it simply shows the name of the pokecube itself - in this case it would be "bibarel"?  Can they be renamed using a name tag?

**Comment by Thutmose** [comment]
have you tried capturing one, or right clicking it with your watch or pokedex? (or looking at it while wearing the watch, then pressing whatever hotkey is set to open it)

**Comment by smmmadden** [comment]
Actually, I did not but now I see that once you do it changes to just their name and provides stats on them. :-)  Looking at it while wearing the watch did nothing.  But moving the watch out of the slot to my hand and clicking, did.

It did also end up throwing a massive exception in the logs though.  https://pastebin.com/U9k7LesC

**Comment by Thutmose** [comment]
that log is unrelated, seems sponge doesn't like how one of the AI things runs, I can look into getting that dealt with, I think that particular thing it is complaining about I have  way to fix, just forgot to in that particular case

**Comment by Thutmose** [comment]
fixed that sponge log thingy for next release.
